PREFIX :      <http://michaeldebellis.com/people/>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl:   <http://www.w3.org/2002/07/owl#>


# Listing 7-1 SPARQL Test Data Generated by ChatGPT
INSERT DATA { ##############################################################
# Adult ≡ Person ∧ has_age ≥ 18
# Child ≡ Person ∧ has_age < 18
# Testing strategy: Equivalence Partitioning + Boundary Value # Analysis ##############################################################
# EP invalid partition (age < 18) + BVA edge just below
:Alice_Person_17 a :Person, :Test_Data ; :has_age "17"^^xsd:integer .
  # EP valid partition (age ≥ 18) + BVA exact boundary
:Bob_Person_18   a :Person, :Test_Data ; :has_age "18"^^xsd:integer .
# EP valid partition (age ≥ 18) + BVA just above boundary
  :Carol_Person_19 a :Person, :Test_Data ; :has_age "19"^^xsd:integer .
# EP edge case: no value at all (Open World Assumption test)
  :Dana_No_Age     a :Person, :Test_Data . ##############################################################
# Boy ≡ Child ⊓ has_Gender Male
# Girl ≡ Child ⊓ has_Gender Female
# --- EP partitions by gender; BVA age < 18 ##############################################################
# Valid partition: Child + Male → should infer Boy
  :Eddie_Age12_Male    a :Person, :Test_Data ; :has_age "12"^^xsd:integer ; :has_Gender :Male .
  # Valid partition: Child + Female → should infer Girl
  :Fiona_Age12_Female  a :Person, :Test_Data ; :has_age "12"^^xsd:integer ; :has_Gender :Female .
  # Partition outside definition: Child + Non_Binary → should infer Child, but not Boy/Girl
  :Noah_Age12_NonBinary a :Person, :Test_Data ; :has_age "12"^^xsd:integer ; :has_Gender :Non_Binary .
##############################################################
# Man ≡ Adult ⊓ has_Gender Male
# Woman ≡ Adult ⊓ has_Gender Female
##############################################################
  :George_Age30_Male   a :Person, :Test_Data ; :has_age "30"^^xsd:integer ; :has_Gender :Male .
  :Hannah_Age30_Female a :Person, :Test_Data ; :has_age "30"^^xsd:integer ; :has_Gender :Female .
  :Indy_Age30_NonBinary a :Person, :Test_Data ; :has_age "30"^^xsd:integer ; :has_Gender :Non_Binary .
##############################################################
# Functional property: has_Gender (ObjectProperty)
# --- EP: single gender (valid) vs multiple genders (invalid) ##############################################################
:Alex_DualGender a :Person, :Test_Data ; :has_age "25"^^xsd:integer ;
                   :has_Gender :Male, :Female .
:Male owl:differentFrom :Female .   # force inconsistency
##############################################################
# Functional property: has_age (DatatypeProperty) ##############################################################
:PolyAgePerson a :Person, :Test_Data ;
                 :has_age "21"^^xsd:integer ,"22"^^xsd:integer.
##############################################################
# Employee ≡ Person ∧ has_employer some Agent
# Self_Employee ⊑ Employee
##############################################################
:IBM_Corp a :Corporation, :Organization, :Test_Data .
# Valid partition: employer is Organization (Agent)
:Shannon_Employee a :Person, :Test_Data ; :has_employer :IBM_Corp .
# Edge case: employer is a Person (still an Agent, but less typical)
:Einstein_Person a :Person, :Test_Data .
:Eve_EmployeeToPerson a :Person, :Test_Data ; :has_employer :Einstein_Person .
# Self_Employee case
:Sam_SelfEmployed a :Self_Employee, :Person, :Test_Data ;
                    :has_employer :Sam_SelfEmployed .
##############################################################
# Spouse: Symmetric + Irreflexive  ##############################################################
# One-sided assertion → should infer symmetry
:Grace_Hopper   a :Person, :Test_Data ; :has_Spouse :Vincent_Foster .
:Vincent_Foster a :Person, :Test_Data .
# Optional violation (BVA for irreflexivity)
:Grace_Hopper :has_Spouse :Grace_Hopper .
##############################################################
# Parents: has_Father (range Man), has_Mother (range Woman)
##############################################################
:Child_X  a :Person, :Test_Data ; :has_Father :Father_X ; :has_Mother :Mother_X .
  :Father_X a :Man, :Test_Data .
  :Mother_X a :Woman, :Test_Data .}
