PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX :  <https://michaeldebellis.com/people/>

#Important: THESE QUERIES WILL NOT WORK IN SNAP SPARQL. You need to use AllegroGrap, GraphDB, Stardog
#or some other tool that supports the full SPARQL specification
#First, some fairly simple queries that aren't supported in Snap SPARQL. 

#Find all the predicates that connect Einstein and Godel
SELECT *
WHERE {:Albert_Einstein ?p :Kurt_Godel}

#Find all the predicates that connect Einstein to anything
SELECT *
WHERE {:Albert_Einstein ?p ?o}

#Find all the predicates that connect Einstein to anything
#Except for rdf:type
SELECT *
WHERE {:Albert_Einstein !rdf:type ?o}

# These queries show examples of using some of the SPARQL Path Operators such as +
# List all people that Einstein has a social relationship with
SELECT *
WHERE {:Albert_Einstein :has_social_relationship ?person}

#Lists the people that Einstein has a social relation with
#The * path operator includes people who have a social relation with Einstein's social relations
SELECT *
WHERE {:Albert_Einstein :has_social_relationship* ?person}

#Gives the same set of people, except by not using the path operator we get the properties as well as the nodes
SELECT *
WHERE {:Albert_Einstein :has_social_relationship ?person.
       ?person :has_social_relationship ?person1.}

#Lists all the people who have a child or a pet
SELECT *
WHERE {?person :has_child|:has_pet ?living_thing}
